CREATE TABLE MEDECIN (
    numRPPS INTEGER PRIMARY KEY,
    nomM VARCHAR(255) NOT NULL,
    prenomM VARCHAR(255) NOT NULL,
    specialite VARCHAR(255) NOT NULL,
    ville VARCHAR(255) NOT NULL,
    adresse VARCHAR(255) NOT NULL
);

CREATE TABLE PATIENT (
    numSS INTEGER PRIMARY KEY,
    nomP CHAR(50),
    prenomP CHAR(50),
    sexe CHAR(1),
    dateNaiss DATE,
    numRPPS INTEGER,
    FOREIGN KEY (numRPPS) REFERENCES MEDECIN(numRPPS)

);
