CREATE TABLE PATIENT (
    numSS INTEGER PRIMARY KEY AUTOINCREMENT,
    nomP CHAR(50),
    prenomP CHAR(50),
    sexe CHAR(1),
    dateNaiss DATE,
    numRPPS INTEGER
    FOREIGN KEY (numRPPS) REFERENCES 

)